name: HealthTrack CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run unit tests
      run: |
        if [ -d "tests/unit" ]; then
          pytest tests/unit/ -v
        else
          echo "⚠️ No unit tests directory found"
          exit 0
        fi

  functional-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest selenium webdriver-manager
        
    - name: Start Flask app
      run: |
        nohup python src/app.py > flask.log 2>&1 &
        sleep 5  # Espera que la app inicie
        
    - name: Run functional tests
      run: |
        if [ -f "tests/functional/test_selenium.py" ]; then
          pytest tests/functional/ -v
        else
          echo "⚠️ No functional tests found"
          exit 0
        fi
        
    - name: Get Flask logs (debug)
      if: always()
      run: cat flask.log

  performance-tests:
    needs: functional-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Locust
      run: pip install locust
        
    - name: Run performance test
      run: |
        nohup python src/app.py > flask.log 2>&1 &
        sleep 5
        locust -f tests/performance/locustfile.py \
          --host=http://localhost:5000 \
          --headless \
          --users 50 \
          --spawn-rate 5 \
          --run-time 2m \
          --csv=perf_results
          
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: perf_results*